spring.application.name=payment-gateway
server.port=8100

gateway.payment-orchestrator.base-url=http://localhost:8999
gateway.promotion.base-url=http://localhost:8083
gateway.purchase-status.ttl-seconds=86400