spring.application.name=billing-ledger-service
server.port=8096

spring.datasource.url=jdbc:mysql://localhost:3306/billing_ledger
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.consumer.group-id=billing-ledger-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

app.kafka.topic.payment-events=commerce.payment.events.v1
